name: CI with contracts run through command line

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
      with:
        path: main
    - name: Set up JRE 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '17'
        java-package: 'jre'
    - name: Setup python
      uses: actions/setup-python@v4
      with:
          python-version: '3.8'
          cache: 'pip'
    - name: Run pip install
      working-directory: main
      run: pip install -r requirements.txt
    - name: Run contract as tests with Specmatic Python Extensions
      working-directory: main
      run: pytest test -v --junitxml contract-test-reports/TEST-junit-jupiter.xml --cov=api --cov-report=term > coverage.txt
    - name: Publish contract test report
      uses: mikepenz/action-junit-report@v3
      if: always()
      with:
        report_paths: '**/contract-test-reports/TEST-*.xml'
    - name: Pytest coverage comment
      uses: MishaKav/pytest-coverage-comment@main
      with:
        pytest-coverage-path: main/coverage.txt
        junitxml-path: main/contract-test-reports/TEST-junit-jupiter.xml
        title: Coverage Report
        badge-title: Specmatic Order API Python Coverage
        hide-badge: false
        hide-report: false
        create-new-comment: false
        hide-comment: false
        report-only-changed-files: false
        remove-link-from-badge: false


